### ISSUE TITLE
Fetching +A and -A profile datas

### ISSUE THREAD

**Issue by wrobi** [ZsBT/hass-w1000-portal#5] opened 2022-11-23 20:59 UTC
[feature-request]
Is there any way to process the 15-minute data? 
I mean the +A and -A profiles.
I know they can be half a day late, but it would be nice to see the consumption and recharge data on the Home Assistant Energy Dashboard.
BTW it's a very useful product, thanks a lot.

**Comment by ZsBT** [comment] 2022-11-24 09:42
Yes I already wanted it to be implemented. There are a few concerns:

- EON however has the data in 15-min periods, it publishes data once or twice day on the Portal (they confirmed by email when I asked).
- HA does not support a sensor reading to be placed in the past (I already send attribute "last_updated" accordingly with this integration, no success)
- I could by achieved by inserting records directly to the database, which is quite dangerous. If I was able to do it correctly, in a future HA release it can break, which means the whole DB can be corrupted. This case, HA drops the db a creates a new one, meaning all historical data will be lost
- My best tip would be the [History Stats](https://www.home-assistant.io/integrations/history_stats/) feature, however that is a quite basic stuff probably not eligible (yet?) for energy measurements. 

Overall, I won't give up. But, at least one or two of the abovements should improve to make something useful.

**Comment by wrobi** [comment] 2022-11-24 19:36
I found this articles:
https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406/9
I hope it helps.

**Comment by ZsBT** [comment] 2022-11-24 20:16
That looks promising; thanks a lot @wrobi for the finding.
(  [permalink](https://github.com/janmolemans/huawei_fusionsolar/blob/ea2b58ee8a537b02ab1a367107f77c5960ac9f7a/sensor.py#L101) for me to an example )

**Comment by wrobi** [comment] 2022-11-25 20:05
I tried to implement it, but I can't give a valid datetime value to the function.
This is my modified __init__.py:
`"""
    Support for W1000 energy portal
    
    Thanks to https://github.com/amargo/ for the login session ideas
    
"""
import logging

import aiohttp
import voluptuous as vol

from homeassistant.core import callback, HomeAssistant
from homeassistant.helpers import discovery
import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.event import async_track_utc_time_change
from homeassistant.const import (
    CONF_SCAN_INTERVAL,
    POWER_WATT
)
import homeassistant.util.dt as dt_util

from bs4 import BeautifulSoup
import requests, yaml, re
from datetime import datetime, timedelta, timezone

from homeassistant.components.recorder.models import StatisticData, StatisticMetaData
from homeassistant.components.recorder.statistics import (
    async_add_external_statistics,
    get_last_statistics,
    async_import_statistics
)

_LOGGER = logging.getLogger(__name__)

DOMAIN = "w1000-energy-monitor"

CONF_ENDPOINT = "url"
CONF_USERNAME = "login_user"
CONF_PASSWORD = "login_pass"
CONF_REPORTS = "reports"
CONF_INTERVAL = "scan_interval"

CONFIG_SCHEMA = vol.Schema(
    {
        DOMAIN: vol.Schema(
            {
                vol.Required(CONF_USERNAME): cv.string,
                vol.Required(CONF_PASSWORD): cv.string,
                vol.Required(CONF_REPORTS): cv.string,
                vol.Optional(CONF_INTERVAL, default=60): cv.positive_int, # minutes
                vol.Optional(CONF_ENDPOINT, default="https://energia.eon-hungaria.hu/W1000"): cv.string,
            }
        )
    },
    extra=vol.ALLOW_EXTRA,
)



async def async_setup(hass, config):
    scan_interval = config[DOMAIN][CONF_INTERVAL]

    monitor = w1k_Portal(hass, config[DOMAIN][CONF_USERNAME], config[DOMAIN][CONF_PASSWORD], config[DOMAIN][CONF_ENDPOINT], config[DOMAIN][CONF_REPORTS] )
    hass.data[DOMAIN] = monitor

    now = dt_util.utcnow()
    async_track_utc_time_change(
        hass,
        monitor.update,
        minute=range(now.minute % scan_interval, 60, scan_interval),
        second=now.second,
    )

    hass.async_create_task(
        discovery.async_load_platform(hass, "sensor", DOMAIN, {}, config)
    )

    return True



class w1k_API:

    def __init__(self, username, password, endpoint, reports):

        self.username = username
        self.password = password
        self.account_url = endpoint+"/Account/Login"
        self.profile_data_url = endpoint + "/ProfileData/ProfileData"
        self.lastlogin = None
        self.reports = [ x.strip() for x in reports.split(",") ]
        self.session = None


    async def request_data(self, ssl=True):
        
        ret = {}
        for report in self.reports:
            _LOGGER.debug("reading report "+report)
            retitem = await self.read_reportname(report)
            ret[report] = retitem[0]
        
        return ret
        

    def mysession(self):
        if self.session:
            return self.session
    
        jar = aiohttp.CookieJar(unsafe=True)
        self.session = aiohttp.ClientSession(cookie_jar=jar)
        return self.session

    async def login(self, ssl=False):
        try:
            session = self.mysession()
            async with session.get(
                url=self.account_url, ssl=ssl
            ) as resp:
                content = (await resp.content.read()).decode("utf8")
                status = resp.status
            
            index_content = BeautifulSoup(content, "html.parser")
            dome = index_content.select('#pg-login input[name=__RequestVerificationToken]')[0]
            self.request_verification_token = dome.get("value")

            payload = {
                "__RequestVerificationToken": self.request_verification_token,
                "UserName": self.username,
                "Password": self.password,
            }
            
            header = {}
#            header["User-Agent"] =  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
#            header["Referer"] = self.account_url

            async with session.post(
                url=self.account_url, data=payload, ssl=ssl
            ) as resp:
                content = (await resp.content.read()).decode("utf8")
                status = resp.status
            
            _LOGGER.debug("resp status http "+str(status) )
            match = re.findall( r'W1000.start\((.+)sessionTimeout', content.replace("\n", " ") )
            
            if not status == 200:
                _LOGGER.error("Login failed.")
                _LOGGER.debug("HTML page: "+content)
                _LOGGER.debug("Index page was: "+index_content)
                return False
                
            if len(match)==0:
                _LOGGER.error("could not find session data. invalid or locked account?")
                _LOGGER.debug("HTML page: "+content)
                return False
            
            respob = yaml.safe_load(match[0]+"}")
            self.currentUser = respob['currentUser']
            self.workareas = respob['workareas']
            self.lastlogin = datetime.utcnow()
            
            for workarea in self.workareas:
                for window in workarea['windows']:
                    _LOGGER.debug("found report "+window['name']+" in workarea "+workarea['name'] )

            return True
            
        except Exception as ex:
            availability = 'Offline'
            _LOGGER.error("exception at login")
            print(datetime.now(), "Error retrive data from {0}.".format(str(ex)))
            
    
    
    async def read_reportname(self, reportname: str):
        loginerror = False
        if not self.lastlogin or self.lastlogin + timedelta(minutes=10) < datetime.utcnow():
            loginerror = not await self.login()
        
        if loginerror:
            return [None]
        
        for workarea in self.workareas:
            for window in workarea['windows']:
                if window['name'] == reportname:
                    return await self.read_reportid( int(window['reportid']), reportname )
        
        _LOGGER.error("report "+reportname+" not found")
        return [None]
        

    async def read_reportid(self, reportid: int, reportname: str, ssl=True):
        now = datetime.utcnow()

        loginerror = False
        if not self.lastlogin or self.lastlogin + timedelta(hours=1) < datetime.utcnow():
            loginerror = not await self.login()
        
        if loginerror:
            return None
            
        since = (now + timedelta(days=-2)).strftime("%Y-%m-%dT00:00:00")
        until = (now + timedelta(days=0 )).strftime("%Y-%m-%dT%H:00:00")
        
        params = {
            "page": 1,"perPage": 96*3,
            "reportId": reportid,
            "since": since,
            "until": until,
            "_": (now - timedelta(hours=3)).strftime("%s557")
        }
        
        session = self.mysession()
        
        async with session.get(
            url=self.profile_data_url, data=params, ssl=ssl
        ) as resp:
            jsonResponse = await resp.json()
            status = resp.status
        
        if status == 200:
            lastvalue = None
            unit = None
            lasttime = None
            ret = []
            statistic_id = f"sensor.{reportname}"
            statistics = []
            for window in jsonResponse:
                unit = window['unit']
                for data in window['data']:
                    dt=datetime.fromisoformat(data['time']+"+01:00").replace(tzinfo=timezone.utc)
                    # _LOGGER.debug(dt)
                    if data['value'] > 0:
                        statistics.append(
                             StatisticData(
                                 start=dt,
                                 sum=data['value']*1000
                             )
                        )
                        lastvalue = round(data['value'],1)
                        lasttime = data['time']
                ret.append( {'curve':window['name'], 'last_value':lastvalue, 'unit':window['unit'], 'last_time':lasttime} )
                metadata = StatisticMetaData(
                    has_mean=False,
                    has_sum=True,
                    name=reportname,
                    source='recorder',
                    statistic_id=statistic_id,
                    unit_of_measurement=POWER_WATT, # kilo watt not allowed by statistics
                )
                _LOGGER.debug("adding statistic: "+statistic_id+" count: "+str(len(statistics)))
                async_import_statistics(self._hass, metadata, statistics)                
        else:
            _LOGGER.error("error http "+str(status) )
            print( jsonResponse )

        return ret








class w1k_Portal(w1k_API):

    def __init__(self, hass, username, password, endpoint, reports):
        super().__init__(username, password, endpoint, reports)
        self._hass = hass
        self._data = {}
        self._update_listeners = []

    def get_data(self, name):
        return self._data.get(name)

    async def update(self, *args):
        json = await self.request_data()
        self._data = self._prepare_data(json)
        self._notify_listeners()

    def _prepare_data(self, json):
        out = {}
        for report in json:
            dta = json[report]
            if dta and 'curve' in dta:
                out[report] = { 'state': dta['last_value'], 'unit':dta['unit'], 'attributes':{
                    'curve':dta['curve'],
                    'generated':dta['last_time'],
                    'state_class': 'measurement',
                }}
                if dta['unit'].endswith('W'):
                    out[report]['attributes']['device_class'] = 'power'
                if dta['unit'].endswith('Wh'):
                    out[report]['attributes']['device_class'] = 'energy'
        return out

    def add_update_listener(self, listener):
        self._update_listeners.append(listener)
        _LOGGER.debug(f"registered sensor: {listener.entity_id}")
        listener.update_callback()


    def _notify_listeners(self):
        for listener in self._update_listeners:
            listener.update_callback()
        _LOGGER.debug("Notifying all listeners")
`

**Comment by wrobi** [comment] 2022-11-26 02:31
It seems to be I implemented successfully, but it need to test.
You will find it on my fork.
![image](https://user-images.githubusercontent.com/26403578/204068991-0f9cc5af-e569-40dc-852f-f77217a1718b.png)
(Nov 14th was a sunny day)

**Comment by wrobi** [comment] 2022-11-26 09:07
I figured out the datas were offseted by 1 hour, so I fixed it. But I didn't find automatic solution to determine DST, Other things to do is to somehow determine the daily starting value and then add the changes.
![image](https://user-images.githubusercontent.com/26403578/204080961-517d6ceb-ef7b-47b9-bc6b-b0006de0269f.png)
Yesterday we had a blackout at 8:30 to 10:00

**Comment by lazlykama** [comment] 2022-11-28 15:50
@wrobi Looking great thank you your work. I hope @ZsBT merge this soon. :rocket: Now the energy dashboard looking very strange because the one spike in the middle of the night from the previous day, and because this the energy balance wrong too.

~~Are you sure it's avaiable for everybody? I can't dig 15 minutes data even from the official website.~~ I found called as `+A` and `-A` based on your sourcecode :+1: 

The +1 hour probably not static, it's because Hungary not in daylight saving time at the moment ("winter time"), it should +2 in summer. So it's arrive in UTC time simple.

**Comment by wrobi** [comment] 2022-11-28 16:14
We are working on it, but it's still in the testing phase and the code changes daily. Anyway, a bit pretentiously, we could say, like Szilárd Leó in the Manhattan Project: -We could also continue in Hungarian. :)

**Comment by ZsBT** [comment] 2022-12-02 08:30
[Discussing](https://github.com/ZsBT/hass-w1000-portal/discussions/8) [HU]

**Comment by ZsBT** [comment] 2022-12-05 20:19
- implemented by commit 9f23f227e449e17f5942495638e326c585ef27c8
- keeping open for a while

**Comment by lazlykama** [comment] 2022-12-06 21:46
> unfortunately the start day of measurement looks like this, as Home Assistant does not support an "initial value" of a meter in statistics

I'm wondering maybe we can define an intial shift in EON's site. If I understand right we could shift the measurement with a static value here:
![Screenshot from 2022-12-06 22-40-08](https://user-images.githubusercontent.com/118392651/206029698-2592737a-8bc2-48fc-928c-b01238a410ba.png)

**Comment by ZsBT** [comment] 2022-12-07 20:06
closing as completed, listening to discussion https://github.com/ZsBT/hass-w1000-portal/discussions/8

**Closed by ZsBT** 2022-12-07 20:06 UTC
Labels: enhancement, on hold
